### ISSUE TITLE
chromosome names

### ISSUE THREAD

**Issue by igordot** [smarco/gem3-mapper#19]
I am using the SourceForge binaries, since it seems `gem-mappability` is not available in the GitHub version. I tried to index a genome with contigs like:

```
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
```

The old indexer parses those contig names as `chr1 AC` (not `chr1`). Is there a way to resolve that?

**Comment by smarco** [comment]
This repository is for the latest release of the gem-mapper (GEMv3). If you have any issue with the old binaries (GEMv2) don't hesitate to contact the developers by email (Paolo Ribeca <paolo.ribeca@gmail.com> and Santiago Marco Sola <santiagomsola@gmail.com>). 

In this case, the old GEMv2 parses the whole line and there is no option to do otherwise. The easiest solution is to adapt the input mFASTA to remove trailing tags on the sequence name (i.e., leave ">chr1" and remove the rest).

Sorry for the inconvenience,
